function testMeBaby(obj)
  println("testMeBaby says a different thing !")
  println(typeof(obj))
  println("-------------")
  println(obj.a.dict)
  println(obj.a.dat)
  println("-------------")
  println(obj.b)
  println("-------------")
end
